version: '2'

services:
  db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: notes
        MYSQL_USER: notes-api
        MYSQL_PASSWORD: notes-api
        MYSQL_ROOT_PASSWORD: notes-api
  app:
      depends_on:
        - db
      build: nodejs
      links:
        - db
  proxy: 
    depends_on:
        - app
    image: nginx:1-alpine
    volumes:
      - ./ngnix/:/etc/nginx/conf.d/
    links:
      - app
    ports:
      - 80:80
      
