version: '2.1'

services:
  db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./dump:/docker-entrypoint-initdb.d
      environment:
        MYSQL_DATABASE: notes
        MYSQL_USER: notes-api
        MYSQL_PASSWORD: notes-api
        MYSQL_ROOT_PASSWORD: notes-api
      healthcheck:
        test: "mysql --user=root --password=notes-api --execute \"SHOW DATABASES;\""
        interval: 5s
        timeout: 200s
        retries: 40
  app:
      depends_on:
        db:
          condition: service_healthy
      build: nodejs
      links:
        - db
  proxy: 
    depends_on:
        - app
    image: nginx:1-alpine
    volumes:
      - ./ngnix/:/etc/nginx/conf.d/
    links:
      - app
    ports:
      - 80:80
      
