---
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: Install git 
    yum:
      name: git
      state: latest
    become: yes

  - name: Clone repo
    git:
      repo: https://github.com/leonaugusto16/api-example-infra.git
      dest: "{{ directory_project }}"
    become: yes

